/* Biblioteca de ejercicios: nombre, grupo muscular, técnica, errores comunes y fotos.
   unit:'time' = se mide en segundos sostenidos, no en peso x reps.
   Fotos: free-exercise-db (yuhonas) — licencia Unlicense, dominio público. */
var GRUPOS={"cuadriceps": "Cuádriceps", "isquios": "Isquios y glúteo", "pecho": "Pecho", "hombro": "Hombro", "espalda": "Espalda", "brazos": "Brazos", "core": "Core", "gemelos": "Gemelos"};
var EXDB={
"abdominales":{n:"Crunch en polea",g:"core",
 cue:"De rodillas, cuerda detrás de la nuca. Enrollá la columna llevando los codos a los muslos.",
 tips:["Tirar con los brazos. Las manos quedan fijas al lado de la cabeza.","Flexionar la cadera en vez de la columna. Acercá el esternón a la pelvis.","Ir rápido y rebotar. Controlá la vuelta."],
 img:["img/abdominales-0.jpg",
      "img/abdominales-1.jpg"]},
"aperturas":{n:"Aperturas con mancuernas",g:"pecho",
 cue:"Codos apenas doblados y fijos. Abrí en arco hasta sentir el pecho y volvé juntando.",
 tips:["Doblar y estirar el codo: eso ya es un press, no una apertura.","Bajar demasiado y forzar el hombro. Parás a la altura del pecho.","Usar demasiado peso. Es un ejercicio de estiramiento, no de fuerza."],
 img:["img/aperturas-0.jpg",
      "img/aperturas-1.jpg"]},
"bulgara":{n:"Zancada búlgara",g:"cuadriceps",
 cue:"Pie de atrás sobre el banco, la pierna de adelante hace todo. Bajá recto, sin irte adelante.",
 tips:["Poner el pie de adelante muy cerca del banco: te tranca la rodilla.","Perder el equilibrio por mirar al piso. Fijá la vista en un punto.","Empujar con la pierna de atrás. Esa solo acompaña."],
 img:["img/bulgara-0.jpg",
      "img/bulgara-1.jpg"]},
"curl-biceps":{n:"Curl de bíceps con barra",g:"brazos",
 cue:"Codos pegados al costado del torso y quietos. Subí la barra hasta el pecho sin mover los hombros.",
 tips:["Balancearse hacia atrás para subir. Apoyá la espalda en una pared.","Adelantar los codos al subir: ahí entra el hombro y sale el bíceps.","Bajar solo hasta la mitad. Estirá el brazo casi del todo."],
 img:["img/curl-biceps-0.jpg",
      "img/curl-biceps-1.jpg"]},
"curl-femoral":{n:"Curl femoral acostado",g:"isquios",
 cue:"Boca abajo, cadera pegada a la banca. Llevá los talones hacia la cola apretando el isquio arriba.",
 tips:["Levantar la cadera de la banca para ayudarte: si se despega, es mucho peso.","Rango parcial. Bajá hasta casi estirar del todo.","Ir muy rápido. Bajá contando 2 segundos."],
 img:["img/curl-femoral-0.jpg",
      "img/curl-femoral-1.jpg"]},
"curl-femoral-sentado":{n:"Curl femoral sentado",g:"isquios",
 cue:"Sentado con el respaldo firme, empujá los talones hacia abajo y atrás apretando arriba.",
 tips:["Despegar la espalda del respaldo. Quedate pegado todo el movimiento.","Soltar el peso de golpe en la vuelta.","Almohadilla mal ajustada: va sobre el tendón de Aquiles, no sobre el gemelo."],
 img:["img/curl-femoral-sentado-0.jpg",
      "img/curl-femoral-sentado-1.jpg"]},
"curl-martillo":{n:"Curl martillo",g:"brazos",
 cue:"Palmas enfrentadas todo el movimiento, codos quietos al costado. Subí sin balanceo.",
 tips:["Rotar la muñeca al subir. En este el agarre no cambia nunca.","Usar los hombros para arrancar el movimiento.","Soltar el peso en la bajada en vez de controlarlo."],
 img:["img/curl-martillo-0.jpg",
      "img/curl-martillo-1.jpg"]},
"dominadas":{n:"Dominadas",g:"espalda",
 cue:"Agarre un poco más ancho que los hombros. Subí llevando el pecho a la barra, no el mentón.",
 tips:["Balancearse para subir. Si no te salen limpias, usá la asistida.","Rango parcial: bajá hasta estirar casi del todo cada rep.","Encoger los hombros al colgarte. Activá la espalda antes de subir."],
 img:["img/dominadas-0.jpg",
      "img/dominadas-1.jpg"]},
"elevaciones-laterales":{n:"Elevaciones laterales",g:"hombro",
 cue:"Codos apenas doblados, subí las mancuernas a los costados hasta la altura del hombro.",
 tips:["Subir más allá del hombro: de ahí para arriba trabaja el trapecio.","Usar impulso balanceando el cuerpo.","Encoger los hombros al subir. Cuello largo, hombros abajo."],
 img:["img/elevaciones-laterales-0.jpg",
      "img/elevaciones-laterales-1.jpg"]},
"encogimientos":{n:"Encogimientos con barra",g:"hombro",
 cue:"Brazos estirados, subí los hombros derecho hacia las orejas y apretá arriba.",
 tips:["Rotar los hombros en círculos. El movimiento es recto, arriba y abajo.","Doblar los codos: los brazos solo sostienen el peso.","Rango mínimo. Subí todo lo que puedas y frená un segundo."],
 img:["img/encogimientos-0.jpg",
      "img/encogimientos-1.jpg"]},
"extension-cuadriceps":{n:"Extensión de cuádriceps",g:"cuadriceps",
 cue:"Sentado, espalda apoyada. Estirá las piernas apretando el cuádriceps arriba un segundo.",
 tips:["Bloquear la rodilla de golpe al final. Llegá a estirar, pero controlado.","Dejar caer el peso al bajar. La bajada lenta es la mitad del trabajo.","Despegar la espalda del respaldo para ayudarte con impulso."],
 img:["img/extension-cuadriceps-0.jpg",
      "img/extension-cuadriceps-1.jpg"]},
"face-pull":{n:"Face pull en polea",g:"hombro",
 cue:"Polea a la altura de la cara. Tirá la cuerda hacia la frente separando las manos, codos altos.",
 tips:["Poner mucho peso y terminar haciendo un remo. Es liviano, de sensación.","Codos caídos. Van a la altura de los hombros o más arriba.","Recorrido corto: llevá las manos hasta los costados de la cara."],
 img:["img/face-pull-0.jpg",
      "img/face-pull-1.jpg"]},
"fondos":{n:"Fondos en paralelas",g:"pecho",
 cue:"Torso apenas inclinado adelante. Bajá hasta que el hombro quede a la altura del codo.",
 tips:["Bajar demasiado poco. Si no llegás al rango, usá la máquina asistida.","Dejar caer los hombros hacia las orejas abajo: mantenelos abajo y firmes.","Soltarse en la bajada. Controlá los 2 segundos de descenso."],
 img:["img/fondos-0.jpg",
      "img/fondos-1.jpg"]},
"gemelos":{n:"Elevación de gemelos de pie",g:"gemelos",
 cue:"Punta del pie en el escalón, talón colgando. Subí lo más alto posible y bajá estirando bien.",
 tips:["Rebotar con el tendón. Frená un segundo abajo antes de subir.","Rango parcial. Bajá el talón por debajo del escalón.","Ir muy rápido. Apretá 1 segundo arriba."],
 img:["img/gemelos-0.jpg",
      "img/gemelos-1.jpg"]},
"gemelos-sentado":{n:"Elevación de gemelos sentado",g:"gemelos",
 cue:"Rodillas a 90° con la almohadilla sobre el muslo. Subí los talones apretando arriba.",
 tips:["Rango corto. Bajá bien el talón hasta estirar.","Ayudarte empujando con las manos sobre la rodilla.","Ir a los saltos. Movimiento lento y con pausa arriba."],
 img:["img/gemelos-sentado-0.jpg",
      "img/gemelos-sentado-1.jpg"]},
"hip-thrust":{n:"Hip thrust",g:"isquios",
 cue:"Omóplatos apoyados en el banco, barra en la cadera. Subí apretando glúteos hasta quedar en línea.",
 tips:["Hiperextender la lumbar arriba. Parás cuando torso y muslo forman una línea.","Levantar el mentón al subir. Mirá adelante-abajo.","Rango corto. Bajá bien la cadera entre repeticiones."],
 img:["img/hip-thrust-0.jpg",
      "img/hip-thrust-1.jpg"]},
"jalon":{n:"Jalón al pecho",g:"espalda",
 cue:"Sentado, pecho arriba y torso apenas inclinado atrás. Llevá la barra a la clavícula.",
 tips:["Tirar por detrás de la nuca: no suma nada y te lastima el hombro.","Usar impulso con todo el cuerpo. El torso casi no se mueve.","Bajar poco. La barra llega a tocar la parte alta del pecho."],
 img:["img/jalon-0.jpg",
      "img/jalon-1.jpg"]},
"peso-muerto":{n:"Peso muerto convencional",g:"isquios",
 cue:"Barra pegada a la canilla, pecho arriba, espalda recta. Empujá el piso y estirá cadera y rodilla juntas.",
 tips:["Tirar con la espalda en vez de empujar con las piernas. Arranca desde el piso con los pies.","Redondear la lumbar. Si se redondea, bajá el peso, sin excepción.","Alejar la barra del cuerpo: tiene que subir rozando la pierna."],
 img:["img/peso-muerto-0.jpg",
      "img/peso-muerto-1.jpg"]},
"peso-muerto-rumano":{n:"Peso muerto rumano",g:"isquios",
 cue:"Rodillas apenas flexionadas y quietas. Llevá la cadera hacia atrás bajando la barra pegada a la pierna.",
 tips:["Convertirlo en sentadilla doblando las rodillas. Es movimiento de cadera.","Redondear la espalda baja al bajar. Parás donde tu flexibilidad llegue.","Alejar la barra del cuerpo. Tiene que ir rozándote el muslo."],
 img:["img/peso-muerto-rumano-0.jpg",
      "img/peso-muerto-rumano-1.jpg"]},
"plancha":{n:"Plancha",g:"core",unit:"time",
 cue:"Antebrazos y punta de pies. Cuerpo en una línea recta de la cabeza a los talones.",
 tips:["Cadera alta en posición de carpa. Bajala hasta alinearla con los hombros.","Cadera hundida, que te carga la lumbar. Apretá glúteos y meté la pelvis.","Aguantar la respiración. Respirá tranquilo todo el tiempo."],
 img:["img/plancha-0.jpg",
      "img/plancha-1.jpg"]},
"prensa":{n:"Prensa de piernas 45°",g:"cuadriceps",
 cue:"Espalda y cola bien apoyadas. Bajá hasta unos 90° de rodilla y empujá con todo el pie.",
 tips:["Bajar tanto que la cola se despega y se te redondea la lumbar. Ese es tu tope real.","Bloquear las rodillas de golpe arriba. Dejá una flexión mínima.","Empujar con la punta del pie. Usá el medio del pie y el talón."],
 img:["img/prensa-0.jpg",
      "img/prensa-1.jpg"]},
"press-banca":{n:"Press de banca",g:"pecho",
 cue:"Escápulas juntas y hundidas contra el banco, pies firmes en el piso. Bajá la barra al medio del pecho.",
 tips:["Rebotar la barra en el pecho: tocá suave y frená.","Codos abiertos a 90° del torso castiga el hombro. Mantenelos a 45-60°.","Si despegás la cola del banco para levantar más, el peso es demasiado."],
 img:["img/press-banca-0.jpg",
      "img/press-banca-1.jpg"]},
"press-frances":{n:"Press francés acostado",g:"brazos",
 cue:"Acostado, codos apuntando al techo y quietos. Bajá la barra hacia la frente y estirá.",
 tips:["Abrir los codos hacia los costados. Mantenelos apuntando arriba.","Bajar muy rápido cerca de la cara. Controlá siempre.","Mover los hombros: solo se mueve el antebrazo."],
 img:["img/press-frances-0.jpg",
      "img/press-frances-1.jpg"]},
"press-hombro-mancuernas":{n:"Press de hombro con mancuernas",g:"hombro",
 cue:"Sentado con respaldo, mancuernas a la altura de las orejas. Empujá arriba sin chocarlas.",
 tips:["Bajar poco: llegá a que el codo quede a 90°.","Arquear la espalda contra el respaldo para ayudarte.","Codos muy atrás. Mantenelos apenas adelante del cuerpo."],
 img:["img/press-hombro-mancuernas-0.jpg",
      "img/press-hombro-mancuernas-1.jpg"]},
"press-inclinado":{n:"Press inclinado con mancuernas",g:"pecho",
 cue:"Banco a 30-45°. Bajá las mancuernas a la parte alta del pecho, codos a 45°.",
 tips:["Inclinar el banco más de 45° lo convierte en press de hombro.","Chocar las mancuernas arriba. Dejá unos centímetros y mantené tensión.","Codos totalmente abiertos: castiga el hombro sin dar más pecho."],
 img:["img/press-inclinado-0.jpg",
      "img/press-inclinado-1.jpg"]},
"press-mancuernas":{n:"Press plano con mancuernas",g:"pecho",
 cue:"Acostado, mancuernas a la altura del pecho. Empujá arriba y adentro sin bloquear de golpe.",
 tips:["Bajar poco. Llegá a la altura del pecho para estirar bien.","Muñecas dobladas hacia atrás. Mantenelas rectas sobre el antebrazo.","Arquear la lumbar en exceso. Un arco chico está bien, no exagerado."],
 img:["img/press-mancuernas-0.jpg",
      "img/press-mancuernas-1.jpg"]},
"press-militar":{n:"Press militar de pie",g:"hombro",
 cue:"Barra a la altura de la clavícula. Empujá arriba y meté la cabeza apenas la barra pasa la frente.",
 tips:["Arquear la lumbar para empujar más: apretá glúteos y abdomen.","Empujar hacia adelante en vez de arriba.","No metés la cabeza y la barra queda adelante, cargándote el hombro."],
 img:["img/press-militar-0.jpg",
      "img/press-militar-1.jpg"]},
"remo-barra":{n:"Remo con barra",g:"espalda",
 cue:"Torso inclinado a unos 45°, espalda recta. Llevá la barra al ombligo, no al pecho.",
 tips:["Usar impulso de cadera en cada rep. Si te balanceás, bajá el peso.","Espalda redondeada. El pecho abierto todo el movimiento.","Tirar solo con los brazos. Llevá los codos atrás juntando omóplatos."],
 img:["img/remo-barra-0.jpg",
      "img/remo-barra-1.jpg"]},
"remo-mancuerna":{n:"Remo con mancuerna a un brazo",g:"espalda",
 cue:"Una rodilla y una mano en el banco, espalda plana. Llevá la mancuerna a la cadera.",
 tips:["Rotar el torso para levantar más. Hombros paralelos al piso.","Tirar con el brazo. Iniciá llevando el omóplato hacia la columna.","Redondear la espalda. Pecho abierto y cuello neutro."],
 img:["img/remo-mancuerna-0.jpg",
      "img/remo-mancuerna-1.jpg"]},
"remo-polea":{n:"Remo en polea baja",g:"espalda",
 cue:"Espalda firme y torso vertical. Tirá el mango al abdomen juntando los omóplatos.",
 tips:["Balancear el torso adelante y atrás para ayudarte.","Encoger los hombros al tirar. Mantenelos abajo.","Soltar el peso adelante y dejar que te estire la lumbar."],
 img:["img/remo-polea-0.jpg",
      "img/remo-polea-1.jpg"]},
"rueda-abdominal":{n:"Rueda abdominal",g:"core",
 cue:"Abdomen apretado y lumbar sin hundirse. Rodá hacia adelante solo hasta donde controlás.",
 tips:["Ir más lejos de lo que aguantás y hundir la lumbar. Ese es el límite real.","Tirar con los brazos. El abdomen es el que frena y trae la rueda.","Levantar la cola al volver. Cadera firme todo el recorrido."],
 img:["img/rueda-abdominal-0.jpg",
      "img/rueda-abdominal-1.jpg"]},
"sentadilla":{n:"Sentadilla con barra",g:"cuadriceps",
 cue:"Bajá como si te sentaras en una silla que está atrás tuyo, pecho arriba y rodillas siguiendo la línea de los pies.",
 tips:["Las rodillas se meten para adentro al subir — empujá el piso separándolas.","Los talones se despegan: es movilidad de tobillo. Usá calzado plano.","Bajás poco. Apuntá a que la cadera quede al nivel de la rodilla o más abajo."],
 img:["img/sentadilla-0.jpg",
      "img/sentadilla-1.jpg"]},
"triceps-polea":{n:"Extensión de tríceps en polea",g:"brazos",
 cue:"Codos pegados al torso y fijos. Estirá los brazos hacia abajo apretando el tríceps.",
 tips:["Mover los codos adelante y atrás: solo se mueve el antebrazo.","Usar el peso del cuerpo inclinándote encima. Torso quieto.","Doblar las muñecas. Rectas, alineadas con el antebrazo."],
 img:["img/triceps-polea-0.jpg",
      "img/triceps-polea-1.jpg"]},
"zancadas":{n:"Zancadas con mancuernas",g:"cuadriceps",
 cue:"Paso largo hacia adelante, rodilla de atrás baja controlada hasta casi tocar. Torso erguido.",
 tips:["Paso corto: te carga la rodilla en vez del glúteo y el cuádriceps.","Inclinar el torso adelante. Mantenelo vertical, mirada al frente.","Rebotar la rodilla contra el piso. Frená un dedo antes de tocar."],
 img:["img/zancadas-0.jpg",
      "img/zancadas-1.jpg"]},
};
/* alternativas del mismo grupo, para cuando la máquina está ocupada */
function alternativas(key){var g=EXDB[key]&&EXDB[key].g;if(!g)return[];
  return Object.keys(EXDB).filter(function(k){return k!==key&&EXDB[k].g===g});}
